// firebase_options.dart — AUTO-GENERATED by FlutterFire CLI
//
// To generate this file:
//   1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   2. Run: flutterfire configure --project=<your-firebase-project-id>
//   3. This file will be overwritten with your actual Firebase config.
//
// Until then, Firebase.initializeApp() in main.dart uses the default
// google-services.json (Android) and GoogleService-Info.plist (iOS).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('DefaultFirebaseOptions not configured for $defaultTargetPlatform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGYx1kU4SAggKm8YuU_87pVaOjBBx4nY',
    appId: '1:498326761770:android:29dddd0998846905792e53',
    messagingSenderId: '498326761770',
    projectId: 'vitamind-d72ad',
    storageBucket: 'vitamind-d72ad.firebasestorage.app',
  );

  // TODO: Replace with actual values from `flutterfire configure`

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5pQf_v4afrdEfcpsCwpsxUhw0n7IZHI',
    appId: '1:498326761770:ios:8dc653c1e4eb56d7792e53',
    messagingSenderId: '498326761770',
    projectId: 'vitamind-d72ad',
    storageBucket: 'vitamind-d72ad.firebasestorage.app',
    iosBundleId: 'com.example.vitamind',
  );

}