import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../core/cache/cache_service.dart';

/// A burnout risk alert generated by the AI layer, including the risk level
/// (0-100), contributing signals, and an optional recovery plan.
class BurnoutAlert {
  final String id;
  final String userId;
  final int riskLevel;
  final Map<String, dynamic> signals;
  final String? recoveryPlan;
  final bool acknowledged;
  final String date;
  final DateTime createdAt;

  const BurnoutAlert({
    required this.id,
    required this.userId,
    required this.riskLevel,
    required this.signals,
    this.recoveryPlan,
    required this.acknowledged,
    required this.date,
    required this.createdAt,
  });

  factory BurnoutAlert.fromMap(Map<String, dynamic> m) {
    return BurnoutAlert(
      id: m['id'] as String,
      userId: m['user_id'] as String,
      riskLevel: (m['risk_level'] as num).toInt(),
      signals: m['signals'] as Map<String, dynamic>? ?? {},
      recoveryPlan: m['recovery_plan'] as String?,
      acknowledged: m['acknowledged'] as bool? ?? false,
      date: m['date'] as String,
      createdAt: DateTime.parse(m['created_at'] as String),
    );
  }

  BurnoutAlert copyWith({
    bool? acknowledged,
  }) =>
      BurnoutAlert(
        id: id,
        userId: userId,
        riskLevel: riskLevel,
        signals: signals,
        recoveryPlan: recoveryPlan,
        acknowledged: acknowledged ?? this.acknowledged,
        date: date,
        createdAt: createdAt,
      );

  Map<String, dynamic> toMap() => {
        'id': id,
        'user_id': userId,
        'risk_level': riskLevel,
        'signals': signals,
        'recovery_plan': recoveryPlan,
        'acknowledged': acknowledged,
        'date': date,
        'created_at': createdAt.toIso8601String(),
      };
}

class BurnoutService {
  final _supabase = Supabase.instance.client;

  static String _cacheKey(String userId) => 'burnout_latest_$userId';

  /// Returns the most recent burnout alert for the user.
  /// Cached for 1 hour so repeated dashboard visits avoid network calls.
  Future<BurnoutAlert?> fetchLatest(String userId) async {
    final cacheKey = _cacheKey(userId);

    try {
      final data = await _supabase
          .from('burnout_alerts')
          .select()
          .eq('user_id', userId)
          .order('date', ascending: false)
          .limit(1)
          .maybeSingle();

      if (data == null) return null;

      final alert = BurnoutAlert.fromMap(data);

      await CacheService.save(cacheKey, alert.toMap());

      return alert;
    } catch (e) {
      debugPrint('BurnoutService.fetchLatest failed: $e');

      final cached = await CacheService.load<Map<String, dynamic>>(
        cacheKey,
        maxAge: const Duration(hours: 1),
      );
      if (cached != null) {
        debugPrint('BurnoutService: serving cached latest alert');
        return BurnoutAlert.fromMap(cached);
      }
      rethrow;
    }
  }

  /// Marks a burnout alert as acknowledged so it no longer surfaces
  /// as an active warning in the UI.
  Future<void> acknowledge(String alertId) async {
    await _supabase
        .from('burnout_alerts')
        .update({'acknowledged': true})
        .eq('id', alertId);
  }
}
